In [ ]:
# https://tianchi.aliyun.com/competition/entrance/531883/introduction

# 环境配置

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cd drive/MyDrive/'Colab Notebooks'/'心跳信号分类预测'

/content/drive/MyDrive/Colab Notebooks/心跳信号分类预测


# 数据集加载

In [ ]:
import pandas as pd
import pickle

# 数据加载
with open('./train1.pkl', 'rb') as file:
    train1 = pickle.load(file)
train1

id  label         0         1         2         3         4  \
0          0    0.0  0.991230  0.943533  0.764677  0.618571  0.379632   
1          1    0.0  0.971482  0.928969  0.572933  0.178457  0.122962   
2          2    2.0  1.000000  0.959149  0.701378  0.231778  0.000000   
3          3    0.0  0.975795  0.934088  0.659637  0.249921  0.237116   
4          4    2.0  0.000000  0.055816  0.261294  0.359847  0.433143   
...      ...    ...       ...       ...       ...       ...       ...   
99995  99995    0.0  1.000000  0.677705  0.222392  0.257158  0.204690   
99996  99996    2.0  0.926857  0.906347  0.636993  0.415038  0.374745   
99997  99997    3.0  0.925835  0.587384  0.633226  0.632353  0.639283   
99998  99998    2.0  1.000000  0.994762  0.829702  0.458193  0.264162   
99999  99999    0.0  0.925999  0.916477  0.404290  0.000000  0.263034   

              5         6         7  ...  195  196  197  198  199  200  201  \
0      0.190822  0.040237  0.025995  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1      0.132360  0.094392  0.089575  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2      0.080698  0.128376  0.187448  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3      0.281445  0.249921  0.249921  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4      0.453698  0.499004  0.542796  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...         ...       ...       ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  0.054665  0.026152  0.118181  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99996  0.382581  0.358943  0.341359  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99997  0.614292  0.599155  0.517632  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99998  0.240228  0.213766  0.189291  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99999  0.385431  0.361067  0.332708  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       202  203  204  
0      0.0  0.0  0.0  
1      0.0  0.0  0.0  
2      0.0  0.0  0.0  
3      0.0  0.0  0.0  
4      0.0  0.0  0.0  
...    ...  ...  ...  
99995  0.0  0.0  0.0  
99996  0.0  0.0  0.0  
99997  0.0  0.0  0.0  
99998  0.0  0.0  0.0  
99999  0.0  0.0  0.0  

[100000 rows x 207 columns]

In [ ]:
# 数据加载
with open('./test1.pkl', 'rb') as file:
    test1 = pickle.load(file)
test1

id         0         1         2         3         4         5  \
0      100000  0.991571  1.000000  0.631816  0.136230  0.041420  0.102707   
1      100001  0.607553  0.541708  0.340694  0.000000  0.090708  0.164924   
2      100002  0.975273  0.671097  0.686759  0.708482  0.718660  0.716763   
3      100003  0.995635  0.917025  0.521096  0.000000  0.221770  0.404100   
4      100004  1.000000  0.887949  0.745565  0.531720  0.380320  0.224631   
...       ...       ...       ...       ...       ...       ...       ...   
19995  119995  1.000000  0.833028  0.634047  0.639118  0.623852  0.598042   
19996  119996  1.000000  0.825971  0.452105  0.082227  0.000000  0.137119   
19997  119997  0.951745  0.916261  0.667525  0.351985  0.255330  0.197383   
19998  119998  0.927669  0.677190  0.242906  0.055362  0.102120  0.072236   
19999  119999  0.665321  0.527064  0.516663  0.376442  0.489262  0.480725   

              6         7         8  ...      195       196       197  \
0      0.120854  0.123428  0.107915  ...  0.00000  0.000000  0.000000   
1      0.195034  0.168838  0.198844  ...  0.38996  0.386932  0.367251   
2      0.720548  0.701656  0.596579  ...  0.00000  0.000000  0.000000   
3      0.490399  0.527158  0.518056  ...  0.00000  0.000000  0.000000   
4      0.091148  0.057639  0.003915  ...  0.00000  0.000000  0.000000   
...         ...       ...       ...  ...      ...       ...       ...   
19995  0.613583  0.623852  0.628958  ...  0.00000  0.000000  0.000000   
19996  0.201082  0.165688  0.158125  ...  0.00000  0.000000  0.000000   
19997  0.173536  0.141934  0.134542  ...  0.00000  0.000000  0.000000   
19998  0.021010  0.038288  0.048557  ...  0.00000  0.000000  0.000000   
19999  0.459160  0.482864  0.469983  ...  0.00000  0.000000  0.000000   

            198       199       200       201       202       203       204  
0      0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1      0.363917  0.360574  0.357245  0.350575  0.350575  0.350565  0.363874  
2      0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
3      0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
4      0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
...         ...       ...       ...       ...       ...       ...       ...  
19995  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
19996  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
19997  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
19998  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
19999  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  

[20000 rows x 206 columns]

# 模型训练-keras

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Conv1D, Conv2D, MaxPooling2D, Dense, Flatten, LeakyReLU, MaxPool1D, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
import numpy as np

In [ ]:
train_x = train1.drop(['id', 'label'], axis=1)
train_y = tf.keras.utils.to_categorical(train1['label'], 4)
train_x

0         1         2         3         4         5         6    \
0      0.991230  0.943533  0.764677  0.618571  0.379632  0.190822  0.040237   
1      0.971482  0.928969  0.572933  0.178457  0.122962  0.132360  0.094392   
2      1.000000  0.959149  0.701378  0.231778  0.000000  0.080698  0.128376   
3      0.975795  0.934088  0.659637  0.249921  0.237116  0.281445  0.249921   
4      0.000000  0.055816  0.261294  0.359847  0.433143  0.453698  0.499004   
...         ...       ...       ...       ...       ...       ...       ...   
99995  1.000000  0.677705  0.222392  0.257158  0.204690  0.054665  0.026152   
99996  0.926857  0.906347  0.636993  0.415038  0.374745  0.382581  0.358943   
99997  0.925835  0.587384  0.633226  0.632353  0.639283  0.614292  0.599155   
99998  1.000000  0.994762  0.829702  0.458193  0.264162  0.240228  0.213766   
99999  0.925999  0.916477  0.404290  0.000000  0.263034  0.385431  0.361067   

            7         8         9    ...  195  196  197  198  199  200  201  \
0      0.025995  0.031709  0.065524  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1      0.089575  0.030481  0.040499  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2      0.187448  0.280826  0.328261  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3      0.249921  0.241397  0.230670  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4      0.542796  0.616904  0.676696  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...         ...       ...       ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  0.118181  0.244838  0.328949  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99996  0.341359  0.336525  0.317029  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99997  0.517632  0.403803  0.253175  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99998  0.189291  0.203816  0.210866  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99999  0.332708  0.339850  0.350497  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       202  203  204  
0      0.0  0.0  0.0  
1      0.0  0.0  0.0  
2      0.0  0.0  0.0  
3      0.0  0.0  0.0  
4      0.0  0.0  0.0  
...    ...  ...  ...  
99995  0.0  0.0  0.0  
99996  0.0  0.0  0.0  
99997  0.0  0.0  0.0  
99998  0.0  0.0  0.0  
99999  0.0  0.0  0.0  

[100000 rows x 205 columns]

In [ ]:
train_x = train_x.values.reshape(train_x.shape[0], 205, 1)
train_x

array([[[0.9912298 ],
        [0.94353304],
        [0.7646773 ],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.9714822 ],
        [0.92896875],
        [0.57293281],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[1.        ],
        [0.95914876],
        [0.70137828],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       ...,

       [[0.92583516],
        [0.5873839 ],
        [0.63322617],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[1.        ],
        [0.99476217],
        [0.82970177],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.9259994 ],
        [0.91647664],
        [0.40429008],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]]])

In [ ]:
train_y

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]], dtype=float32)

In [ ]:
class CNNModel(tf.keras.Model):
    # 模型定义
    def __init__(self):
        super(CNNModel, self).__init__()           
        self.conv1 = Conv1D(filters=32, kernel_size=5, padding='same', activation=LeakyReLU(alpha=0.001), input_shape = (205, 1))
        self.conv2 = Conv1D(filters=64, kernel_size=5, padding='same', activation=LeakyReLU(alpha=0.001))
        self.conv3 = Conv1D(filters=128, kernel_size=5, padding='same', activation=LeakyReLU(alpha=0.001))
        self.conv4 = Conv1D(filters=256, kernel_size=5, padding='same', activation=LeakyReLU(alpha=0.001))
        self.max_pool1 = MaxPool1D(pool_size=5, strides=2, padding='same')
        self.dropout = Dropout(0.5)
        self.flatten = Flatten()
        # 全连接层
        self.fc1 = Dense(units=512, activation=LeakyReLU(alpha=0.001))
        self.fc2 = Dense(units=4, activation='softmax')
            
    # 前向传播
    def call(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.max_pool1(x)
        x = self.dropout(x)
        x = self.flatten(x)
        # 全连接层
        x = self.fc1(x)
        x = self.fc2(x)
        return x
    
# 创建模型
model = CNNModel()
# 设置优化器
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['mae'])

# 传入训练数据进行训练
model.fit(train_x, train_y, batch_size=128, epochs=5, verbose=1)

Epoch 1/5
782/782 [==============================] - 48s 48ms/step - loss: 0.1440 - mae: 0.0365
Epoch 2/5
782/782 [==============================] - 37s 47ms/step - loss: 0.0627 - mae: 0.0158
Epoch 3/5
782/782 [==============================] - 37s 47ms/step - loss: 0.0415 - mae: 0.0105
Epoch 4/5
782/782 [==============================] - 37s 47ms/step - loss: 0.0323 - mae: 0.0082
Epoch 5/5
782/782 [==============================] - 37s 47ms/step - loss: 0.0249 - mae: 0.0064


In [ ]:
test_x = test1.drop(['id'], axis=1)
test_x = test_x.values.reshape(test_x.shape[0], 205, 1)
test_x

array([[[0.99157137],
        [1.        ],
        [0.63181634],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.60755331],
        [0.54170839],
        [0.3406944 ],
        ...,
        [0.35057524],
        [0.35056459],
        [0.36387441]],

       [[0.97527263],
        [0.67109652],
        [0.68675854],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       ...,

       [[0.95174484],
        [0.91626113],
        [0.66752511],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.92766929],
        [0.67718982],
        [0.2429062 ],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.66532122],
        [0.52706411],
        [0.51666253],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]]])

In [ ]:
y_pred = model.predict(test_x, batch_size=128)
y_pred

array([[9.9859077e-01, 1.4088048e-03, 2.9403746e-10, 3.3254543e-07],
       [3.9447627e-07, 1.1430127e-04, 9.9988532e-01, 4.7710952e-08],
       [2.7839109e-12, 1.6673941e-13, 2.9250344e-09, 1.0000000e+00],
       ...,
       [9.8040644e-03, 9.4611180e-04, 9.8922777e-01, 2.2099191e-05],
       [9.9951398e-01, 4.8599773e-04, 5.1754685e-09, 1.5577661e-11],
       [9.7354513e-01, 3.1220102e-09, 6.8200934e-05, 2.6386712e-02]],
      dtype=float32)

In [ ]:
result = pd.read_csv('./sample_submit.csv')

result['label_0'] = y_pred[:, 0]
result['label_1'] = y_pred[:, 1]
result['label_2'] = y_pred[:, 2]
result['label_3'] = y_pred[:, 3]
result

id       label_0       label_1       label_2       label_3
0      100000  9.985908e-01  1.408805e-03  2.940375e-10  3.325454e-07
1      100001  3.944763e-07  1.143013e-04  9.998853e-01  4.771095e-08
2      100002  2.783911e-12  1.667394e-13  2.925034e-09  1.000000e+00
3      100003  9.999981e-01  1.947322e-06  1.224681e-08  6.164074e-13
4      100004  9.999949e-01  2.518644e-06  2.621960e-06  6.699649e-10
...       ...           ...           ...           ...           ...
19995  119995  9.995598e-01  2.227837e-04  3.745569e-05  1.799075e-04
19996  119996  9.999489e-01  4.612655e-05  4.949140e-06  1.006019e-11
19997  119997  9.804064e-03  9.461118e-04  9.892278e-01  2.209919e-05
19998  119998  9.995140e-01  4.859977e-04  5.175468e-09  1.557766e-11
19999  119999  9.735451e-01  3.122010e-09  6.820093e-05  2.638671e-02

[20000 rows x 5 columns]

In [ ]:
result.to_csv('./predict3-keras-colab.csv', index=False)

In [ ]:
# score:572.7085